### PR TITLE
fix: remove API keys from error messages

### LINKED ISSUE #88: Library leaks API key when an error occurs
Whenever there is an HTTP or validation error at Hubspot, the library will throw a `GuzzleHttp\Exception\ClientException` with a message:

`Uncaught exception 'GuzzleHttp\Exception\ClientException' with message 'Client error: POST https://api.hubapi.com/contacts/v1/contact/createOrUpdate/email/orders@bliinq.com?hapikey=<redacted> resulted in a 400 Bad Request response: <redacted>`

This then gets picked up by our logging systems spreading the API key everywhere. 

I don't think the HTTP 4xx should result in a `GuzzleHttp\Exception\ClientException`, but a nice exception from this library which interprets the results from Hubspot and gives the domain exception message.

### PR DESCRIPTION
**Pull request by atymic**
Closes #88 

I've also added tests to cover the new logic :)

### CODE REVIEW

**Comment by ksvirkou** [comment]
@atymic I'll review it the other day

**Comment by atymic** [comment]
No worries :)

File: src/Exceptions/BadRequest.php [hunk 1]
```diff
@@ -2,6 +2,6 @@
 
 namespace SevenShores\Hubspot\Exceptions;
 
-class BadRequest extends \Exception
+class BadRequest extends HubspotException
```
Comment (atymic) [inline src/Exceptions/BadRequest.php]: This isn't a BC break as they both extend `\Exception`

File: tests/unit/Exception/HubspotExceptionTest.php [hunk 2]
```diff
@@ -0,0 +1,79 @@
...
+use PHPUnit\Framework\TestCase;
+use SevenShores\Hubspot\Exceptions\BadRequest;
+use SevenShores\Hubspot\Exceptions\HubspotException;
+use function GuzzleHttp\Psr7\stream_for;
+
+class HubspotExceptionTest extends TestCase
+{
+    const EXAMPLE_TOKEN = '8907e60c-600d-4af8-a987-191c104a215c';
+
+    public function testCreateExceptionFromGuzzleRequestException()
```
Comment (ksvirkou) [inline tests/unit/Exception/HubspotExceptionTest.php]: it would be better  if you mark all test methods  /** @test */ 
and Could you use static it would be better

File: src/Exceptions/BadRequest.php (hunk 1 above)
Comment (ksvirkou) [reply src/Exceptions/BadRequest.php]: Ok I see

File: tests/unit/Exception/HubspotExceptionTest.php (hunk 2 above)
Comment (atymic) [reply tests/unit/Exception/HubspotExceptionTest.php]: Sorry not sure what you mean by this?
The annotation is only required if the test method doesn't start with `test` (which they do)

Comment (atymic) [reply tests/unit/Exception/HubspotExceptionTest.php]: Test methods should not be static either
https://phpunit.readthedocs.io/en/8.4/writing-tests-for-phpunit.html

Comment (ksvirkou) [reply tests/unit/Exception/HubspotExceptionTest.php]: Sorry for confusion
I'll describe it

Comment (ksvirkou) [reply tests/unit/Exception/HubspotExceptionTest.php]: Regarding annotation
All our tests marked  as /** @test */
to follow project style please

File: tests/unit/Exception/HubspotExceptionTest.php [hunk 3]
```diff
@@ -0,0 +1,79 @@
...
+        $this->assertInstanceOf(HubspotException::class, $hubspotException);
+        $this->assertNull($hubspotException->getResponse());
+    }
+
+    public function testCreateExceptionFromGuzzleClientException()
+    {
+        $e = ClientException::create(
+            new Request(
+                'GET',
+                sprintf('https://api.hubapi.com/deals/v1/deal/12345?access_token=%s', self::EXAMPLE_TOKEN)
```
Comment (ksvirkou) [inline tests/unit/Exception/HubspotExceptionTest.php]: Could You change self to static at this place?
I understand that won’t  be redefined but it is our style
over time we will change all private to protected and self to static (where it is necessary)

File: src/Exceptions/HubspotException.php [hunk 4]
```diff
@@ -2,6 +2,38 @@
...
+     */
+    public function getResponse()
+    {
+        return $this->response;
+    }
+
+    public static function create(RequestException $guzzleException): self
+    {
+        $e = new static(
+            self::sanitizeResponseMessage($guzzleException->getMessage()),
```
Comment (ksvirkou) [inline src/Exceptions/HubspotException.php]: Could You change self to static at this place?
I understand that won’t  be redefined but it is our style
over time we will change all private to protected and self to static (where it is necessary)

File: tests/unit/Exception/HubspotExceptionTest.php [hunk 5]
```diff
@@ -0,0 +1,79 @@
...
+                [],
+                stream_for('<!DOCTYPE html>
+<!--[if lt IE 7]> <html class="no-js ie6 oldie" lang="en-US"> <![endif]-->')
+            )
+        );
+
+        $hubspotException = HubspotException::create($e);
+
+        $this->assertInstanceOf(HubspotException::class, $hubspotException);
+        $this->assertNotContains(self::EXAMPLE_TOKEN, $hubspotException->getMessage());
```
Comment (ksvirkou) [inline tests/unit/Exception/HubspotExceptionTest.php]: Could You change self to static at this place?
I understand that won’t  be redefined but it is our style
over time we will change all private to protected and self to static (where it is necessary)

File: tests/unit/Exception/HubspotExceptionTest.php [hunk 6]
```diff
@@ -0,0 +1,79 @@
...
+{"status":"error","message":"xyz"}
+', $hubspotException->getMessage());
+    }
+
+    public function testCreateExceptionFromGuzzleServerException()
+    {
+        $e = ServerException::create(
+            new Request(
+                'GET',
+                sprintf('https://api.hubapi.com/deals/v1/deal/12345?hapikey=%s', self::EXAMPLE_TOKEN)
```
Comment (ksvirkou) [inline tests/unit/Exception/HubspotExceptionTest.php]: Could You change self to static at this place?
I understand that won’t  be redefined but it is our style
over time we will change all private to protected and self to static (where it is necessary)

File: tests/unit/Exception/HubspotExceptionTest.php [hunk 7]
```diff
@@ -0,0 +1,79 @@
...
+                400,
+                [],
+                stream_for('{"status":"error","message":"xyz"}')
+            )
+        );
+
+        $hubspotException = BadRequest::create($e);
+
+        $this->assertInstanceOf(BadRequest::class, $hubspotException);
+        $this->assertNotContains(self::EXAMPLE_TOKEN, $hubspotException->getMessage());
```
Comment (ksvirkou) [inline tests/unit/Exception/HubspotExceptionTest.php]: Could You change self to static at this place?
I understand that won’t  be redefined but it is our style
over time we will change all private to protected and self to static (where it is necessary)

File: tests/unit/Exception/HubspotExceptionTest.php (hunk 2 above)
Comment (atymic) [reply tests/unit/Exception/HubspotExceptionTest.php]: Updated

**Comment by atymic** [comment]
@ksvirkou 

I've updated as per comments.
